# Generated by Django 5.2.5 on 2025-08-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
